package IDCC.bean;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Account_Id
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Account_Pwd
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    private String accountPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Account_Right
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    private Integer accountRight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Account_Id
     *
     * @return the value of account.Account_Id
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Account_Id
     *
     * @param accountId the value for account.Account_Id
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Account_Pwd
     *
     * @return the value of account.Account_Pwd
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public String getAccountPwd() {
        return accountPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Account_Pwd
     *
     * @param accountPwd the value for account.Account_Pwd
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public void setAccountPwd(String accountPwd) {
        this.accountPwd = accountPwd == null ? null : accountPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Account_Right
     *
     * @return the value of account.Account_Right
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public Integer getAccountRight() {
        return accountRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Account_Right
     *
     * @param accountRight the value for account.Account_Right
     *
     * @mbg.generated Tue Dec 08 20:41:27 CST 2020
     */
    public void setAccountRight(Integer accountRight) {
        this.accountRight = accountRight;
    }
}