package IDCC.bean;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("Account_Id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("Account_Id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("Account_Id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("Account_Id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("Account_Id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("Account_Id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("Account_Id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("Account_Id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("Account_Id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("Account_Id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("Account_Id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("Account_Id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("Account_Id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("Account_Id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountPwdIsNull() {
            addCriterion("Account_Pwd is null");
            return (Criteria) this;
        }

        public Criteria andAccountPwdIsNotNull() {
            addCriterion("Account_Pwd is not null");
            return (Criteria) this;
        }

        public Criteria andAccountPwdEqualTo(String value) {
            addCriterion("Account_Pwd =", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdNotEqualTo(String value) {
            addCriterion("Account_Pwd <>", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdGreaterThan(String value) {
            addCriterion("Account_Pwd >", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdGreaterThanOrEqualTo(String value) {
            addCriterion("Account_Pwd >=", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdLessThan(String value) {
            addCriterion("Account_Pwd <", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdLessThanOrEqualTo(String value) {
            addCriterion("Account_Pwd <=", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdLike(String value) {
            addCriterion("Account_Pwd like", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdNotLike(String value) {
            addCriterion("Account_Pwd not like", value, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdIn(List<String> values) {
            addCriterion("Account_Pwd in", values, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdNotIn(List<String> values) {
            addCriterion("Account_Pwd not in", values, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdBetween(String value1, String value2) {
            addCriterion("Account_Pwd between", value1, value2, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountPwdNotBetween(String value1, String value2) {
            addCriterion("Account_Pwd not between", value1, value2, "accountPwd");
            return (Criteria) this;
        }

        public Criteria andAccountRightIsNull() {
            addCriterion("Account_Right is null");
            return (Criteria) this;
        }

        public Criteria andAccountRightIsNotNull() {
            addCriterion("Account_Right is not null");
            return (Criteria) this;
        }

        public Criteria andAccountRightEqualTo(Integer value) {
            addCriterion("Account_Right =", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightNotEqualTo(Integer value) {
            addCriterion("Account_Right <>", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightGreaterThan(Integer value) {
            addCriterion("Account_Right >", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("Account_Right >=", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightLessThan(Integer value) {
            addCriterion("Account_Right <", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightLessThanOrEqualTo(Integer value) {
            addCriterion("Account_Right <=", value, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightIn(List<Integer> values) {
            addCriterion("Account_Right in", values, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightNotIn(List<Integer> values) {
            addCriterion("Account_Right not in", values, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightBetween(Integer value1, Integer value2) {
            addCriterion("Account_Right between", value1, value2, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountRightNotBetween(Integer value1, Integer value2) {
            addCriterion("Account_Right not between", value1, value2, "accountRight");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundIsNull() {
            addCriterion("Account_EducationBackground is null");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundIsNotNull() {
            addCriterion("Account_EducationBackground is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundEqualTo(String value) {
            addCriterion("Account_EducationBackground =", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundNotEqualTo(String value) {
            addCriterion("Account_EducationBackground <>", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundGreaterThan(String value) {
            addCriterion("Account_EducationBackground >", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("Account_EducationBackground >=", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundLessThan(String value) {
            addCriterion("Account_EducationBackground <", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundLessThanOrEqualTo(String value) {
            addCriterion("Account_EducationBackground <=", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundLike(String value) {
            addCriterion("Account_EducationBackground like", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundNotLike(String value) {
            addCriterion("Account_EducationBackground not like", value, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundIn(List<String> values) {
            addCriterion("Account_EducationBackground in", values, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundNotIn(List<String> values) {
            addCriterion("Account_EducationBackground not in", values, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundBetween(String value1, String value2) {
            addCriterion("Account_EducationBackground between", value1, value2, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountEducationbackgroundNotBetween(String value1, String value2) {
            addCriterion("Account_EducationBackground not between", value1, value2, "accountEducationbackground");
            return (Criteria) this;
        }

        public Criteria andAccountPictureIsNull() {
            addCriterion("Account_Picture is null");
            return (Criteria) this;
        }

        public Criteria andAccountPictureIsNotNull() {
            addCriterion("Account_Picture is not null");
            return (Criteria) this;
        }

        public Criteria andAccountPictureEqualTo(String value) {
            addCriterion("Account_Picture =", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureNotEqualTo(String value) {
            addCriterion("Account_Picture <>", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureGreaterThan(String value) {
            addCriterion("Account_Picture >", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureGreaterThanOrEqualTo(String value) {
            addCriterion("Account_Picture >=", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureLessThan(String value) {
            addCriterion("Account_Picture <", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureLessThanOrEqualTo(String value) {
            addCriterion("Account_Picture <=", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureLike(String value) {
            addCriterion("Account_Picture like", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureNotLike(String value) {
            addCriterion("Account_Picture not like", value, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureIn(List<String> values) {
            addCriterion("Account_Picture in", values, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureNotIn(List<String> values) {
            addCriterion("Account_Picture not in", values, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureBetween(String value1, String value2) {
            addCriterion("Account_Picture between", value1, value2, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountPictureNotBetween(String value1, String value2) {
            addCriterion("Account_Picture not between", value1, value2, "accountPicture");
            return (Criteria) this;
        }

        public Criteria andAccountSexIsNull() {
            addCriterion("Account_Sex is null");
            return (Criteria) this;
        }

        public Criteria andAccountSexIsNotNull() {
            addCriterion("Account_Sex is not null");
            return (Criteria) this;
        }

        public Criteria andAccountSexEqualTo(Integer value) {
            addCriterion("Account_Sex =", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexNotEqualTo(Integer value) {
            addCriterion("Account_Sex <>", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexGreaterThan(Integer value) {
            addCriterion("Account_Sex >", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Account_Sex >=", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexLessThan(Integer value) {
            addCriterion("Account_Sex <", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexLessThanOrEqualTo(Integer value) {
            addCriterion("Account_Sex <=", value, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexIn(List<Integer> values) {
            addCriterion("Account_Sex in", values, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexNotIn(List<Integer> values) {
            addCriterion("Account_Sex not in", values, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexBetween(Integer value1, Integer value2) {
            addCriterion("Account_Sex between", value1, value2, "accountSex");
            return (Criteria) this;
        }

        public Criteria andAccountSexNotBetween(Integer value1, Integer value2) {
            addCriterion("Account_Sex not between", value1, value2, "accountSex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 11 16:49:25 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}