package IDCC.bean;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.Device_Id
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.Device_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.Device_Size
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private String deviceSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.Device_Num
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private Integer deviceNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.Device_Id
     *
     * @return the value of device.Device_Id
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.Device_Id
     *
     * @param deviceId the value for device.Device_Id
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.Device_Name
     *
     * @return the value of device.Device_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.Device_Name
     *
     * @param deviceName the value for device.Device_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.Device_Size
     *
     * @return the value of device.Device_Size
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getDeviceSize() {
        return deviceSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.Device_Size
     *
     * @param deviceSize the value for device.Device_Size
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setDeviceSize(String deviceSize) {
        this.deviceSize = deviceSize == null ? null : deviceSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.Device_Num
     *
     * @return the value of device.Device_Num
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public Integer getDeviceNum() {
        return deviceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.Device_Num
     *
     * @param deviceNum the value for device.Device_Num
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setDeviceNum(Integer deviceNum) {
        this.deviceNum = deviceNum;
    }
}