package IDCC.bean;

public class Mygroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygroup.Group_Id
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygroup.Group_Name
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygroup.Group_Scale
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    private String groupScale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygroup.Group_Id
     *
     * @return the value of mygroup.Group_Id
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygroup.Group_Id
     *
     * @param groupId the value for mygroup.Group_Id
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygroup.Group_Name
     *
     * @return the value of mygroup.Group_Name
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygroup.Group_Name
     *
     * @param groupName the value for mygroup.Group_Name
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygroup.Group_Scale
     *
     * @return the value of mygroup.Group_Scale
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public String getGroupScale() {
        return groupScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygroup.Group_Scale
     *
     * @param groupScale the value for mygroup.Group_Scale
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    public void setGroupScale(String groupScale) {
        this.groupScale = groupScale == null ? null : groupScale.trim();
    }
}