package IDCC.bean;

import java.util.ArrayList;
import java.util.List;

public class SecindexExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public SecindexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrimaryIndexIsNull() {
            addCriterion("Primary_Index is null");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexIsNotNull() {
            addCriterion("Primary_Index is not null");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexEqualTo(Integer value) {
            addCriterion("Primary_Index =", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexNotEqualTo(Integer value) {
            addCriterion("Primary_Index <>", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexGreaterThan(Integer value) {
            addCriterion("Primary_Index >", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Primary_Index >=", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexLessThan(Integer value) {
            addCriterion("Primary_Index <", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexLessThanOrEqualTo(Integer value) {
            addCriterion("Primary_Index <=", value, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexIn(List<Integer> values) {
            addCriterion("Primary_Index in", values, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexNotIn(List<Integer> values) {
            addCriterion("Primary_Index not in", values, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexBetween(Integer value1, Integer value2) {
            addCriterion("Primary_Index between", value1, value2, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andPrimaryIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("Primary_Index not between", value1, value2, "primaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexIsNull() {
            addCriterion("Secondary_Index is null");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexIsNotNull() {
            addCriterion("Secondary_Index is not null");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexEqualTo(Integer value) {
            addCriterion("Secondary_Index =", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexNotEqualTo(Integer value) {
            addCriterion("Secondary_Index <>", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexGreaterThan(Integer value) {
            addCriterion("Secondary_Index >", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Secondary_Index >=", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexLessThan(Integer value) {
            addCriterion("Secondary_Index <", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexLessThanOrEqualTo(Integer value) {
            addCriterion("Secondary_Index <=", value, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexIn(List<Integer> values) {
            addCriterion("Secondary_Index in", values, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexNotIn(List<Integer> values) {
            addCriterion("Secondary_Index not in", values, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexBetween(Integer value1, Integer value2) {
            addCriterion("Secondary_Index between", value1, value2, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecondaryIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("Secondary_Index not between", value1, value2, "secondaryIndex");
            return (Criteria) this;
        }

        public Criteria andSecindexNameIsNull() {
            addCriterion("SecIndex_Name is null");
            return (Criteria) this;
        }

        public Criteria andSecindexNameIsNotNull() {
            addCriterion("SecIndex_Name is not null");
            return (Criteria) this;
        }

        public Criteria andSecindexNameEqualTo(String value) {
            addCriterion("SecIndex_Name =", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameNotEqualTo(String value) {
            addCriterion("SecIndex_Name <>", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameGreaterThan(String value) {
            addCriterion("SecIndex_Name >", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameGreaterThanOrEqualTo(String value) {
            addCriterion("SecIndex_Name >=", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameLessThan(String value) {
            addCriterion("SecIndex_Name <", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameLessThanOrEqualTo(String value) {
            addCriterion("SecIndex_Name <=", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameLike(String value) {
            addCriterion("SecIndex_Name like", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameNotLike(String value) {
            addCriterion("SecIndex_Name not like", value, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameIn(List<String> values) {
            addCriterion("SecIndex_Name in", values, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameNotIn(List<String> values) {
            addCriterion("SecIndex_Name not in", values, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameBetween(String value1, String value2) {
            addCriterion("SecIndex_Name between", value1, value2, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexNameNotBetween(String value1, String value2) {
            addCriterion("SecIndex_Name not between", value1, value2, "secindexName");
            return (Criteria) this;
        }

        public Criteria andSecindexStateIsNull() {
            addCriterion("SecIndex_State is null");
            return (Criteria) this;
        }

        public Criteria andSecindexStateIsNotNull() {
            addCriterion("SecIndex_State is not null");
            return (Criteria) this;
        }

        public Criteria andSecindexStateEqualTo(String value) {
            addCriterion("SecIndex_State =", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateNotEqualTo(String value) {
            addCriterion("SecIndex_State <>", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateGreaterThan(String value) {
            addCriterion("SecIndex_State >", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateGreaterThanOrEqualTo(String value) {
            addCriterion("SecIndex_State >=", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateLessThan(String value) {
            addCriterion("SecIndex_State <", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateLessThanOrEqualTo(String value) {
            addCriterion("SecIndex_State <=", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateLike(String value) {
            addCriterion("SecIndex_State like", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateNotLike(String value) {
            addCriterion("SecIndex_State not like", value, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateIn(List<String> values) {
            addCriterion("SecIndex_State in", values, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateNotIn(List<String> values) {
            addCriterion("SecIndex_State not in", values, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateBetween(String value1, String value2) {
            addCriterion("SecIndex_State between", value1, value2, "secindexState");
            return (Criteria) this;
        }

        public Criteria andSecindexStateNotBetween(String value1, String value2) {
            addCriterion("SecIndex_State not between", value1, value2, "secindexState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secindex
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 22 21:14:14 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}