package IDCC.bean;

public class Secindex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secindex.Primary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private Byte primaryIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secindex.Secondary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private Float secondaryIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secindex.SecIndex_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private String secindexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secindex.SecIndex_State
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    private String secindexState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secindex.Primary_Index
     *
     * @return the value of secindex.Primary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public Byte getPrimaryIndex() {
        return primaryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secindex.Primary_Index
     *
     * @param primaryIndex the value for secindex.Primary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setPrimaryIndex(Byte primaryIndex) {
        this.primaryIndex = primaryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secindex.Secondary_Index
     *
     * @return the value of secindex.Secondary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public Float getSecondaryIndex() {
        return secondaryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secindex.Secondary_Index
     *
     * @param secondaryIndex the value for secindex.Secondary_Index
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setSecondaryIndex(Float secondaryIndex) {
        this.secondaryIndex = secondaryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secindex.SecIndex_Name
     *
     * @return the value of secindex.SecIndex_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getSecindexName() {
        return secindexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secindex.SecIndex_Name
     *
     * @param secindexName the value for secindex.SecIndex_Name
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setSecindexName(String secindexName) {
        this.secindexName = secindexName == null ? null : secindexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secindex.SecIndex_State
     *
     * @return the value of secindex.SecIndex_State
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public String getSecindexState() {
        return secindexState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secindex.SecIndex_State
     *
     * @param secindexState the value for secindex.SecIndex_State
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    public void setSecindexState(String secindexState) {
        this.secindexState = secindexState == null ? null : secindexState.trim();
    }
}