package IDCC.mapper;

import IDCC.bean.PersonnelInfo;
import IDCC.bean.PersonnelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonnelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    long countByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int deleteByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int deleteByPrimaryKey(@Param("staffId") String staffId, @Param("personnelName") String personnelName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int insert(PersonnelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int insertSelective(PersonnelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    List<PersonnelInfo> selectByExample(PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") PersonnelInfo record, @Param("example") PersonnelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel_info
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByExample(@Param("record") PersonnelInfo record, @Param("example") PersonnelInfoExample example);
}