package IDCC.mapper;

import IDCC.bean.Priindex;
import IDCC.bean.PriindexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PriindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    long countByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int deleteByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int deleteByPrimaryKey(String subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int insert(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int insertSelective(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    List<Priindex> selectByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    Priindex selectByPrimaryKey(String subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Priindex record, @Param("example") PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int updateByExample(@Param("record") Priindex record, @Param("example") PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Thu Dec 10 20:41:55 CST 2020
     */
    int updateByPrimaryKey(Priindex record);
}