package IDCC.mapper;

import IDCC.bean.Priindex;
import IDCC.bean.PriindexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PriindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    long countByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int deleteByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int deleteByPrimaryKey(@Param("subjectId") String subjectId, @Param("primaryIndex") Byte primaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int insert(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int insertSelective(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    List<Priindex> selectByExample(PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    Priindex selectByPrimaryKey(@Param("subjectId") String subjectId, @Param("primaryIndex") Byte primaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByExampleSelective(@Param("record") Priindex record, @Param("example") PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByExample(@Param("record") Priindex record, @Param("example") PriindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByPrimaryKeySelective(Priindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priindex
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByPrimaryKey(Priindex record);
}