package IDCC.mapper;

import IDCC.bean.Secindex;
import IDCC.bean.SecindexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    long countByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int deleteByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int deleteByPrimaryKey(Integer primaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int insert(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int insertSelective(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    List<Secindex> selectByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    Secindex selectByPrimaryKey(Integer primaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Secindex record, @Param("example") SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int updateByExample(@Param("record") Secindex record, @Param("example") SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int updateByPrimaryKeySelective(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Tue Dec 22 21:14:14 CST 2020
     */
    int updateByPrimaryKey(Secindex record);
}