package IDCC.mapper;

import IDCC.bean.Secindex;
import IDCC.bean.SecindexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    long countByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int deleteByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int deleteByPrimaryKey(@Param("primaryIndex") Byte primaryIndex, @Param("secondaryIndex") Float secondaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int insert(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int insertSelective(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    List<Secindex> selectByExample(SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    Secindex selectByPrimaryKey(@Param("primaryIndex") Byte primaryIndex, @Param("secondaryIndex") Float secondaryIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") Secindex record, @Param("example") SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByExample(@Param("record") Secindex record, @Param("example") SecindexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByPrimaryKeySelective(Secindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secindex
     *
     * @mbg.generated Wed Aug 11 16:49:25 CST 2021
     */
    int updateByPrimaryKey(Secindex record);
}