package IDCC.mapper;

import IDCC.bean.Subject;
import IDCC.bean.SubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    long countByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int deleteByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int deleteByPrimaryKey(@Param("subjectId") String subjectId, @Param("leaderId") String leaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    List<Subject> selectByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    Subject selectByPrimaryKey(@Param("subjectId") String subjectId, @Param("leaderId") String leaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByExampleSelective(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByExample(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Jul 21 20:27:09 CST 2021
     */
    int updateByPrimaryKey(Subject record);
}